preload = /home/daniel/Pictures/background.jpg
wallpaper = ,/home/daniel/Pictures/background.jpg
wallpaper = DP-3,/home/daniel/Pictures/background.jpg
wallpaper = DP-4,/home/daniel/Pictures/background.jpg
