#!/usr/bin/env bash

# Default search directory
search_dir=~/Documents/code/

# Parse flags
while [[ $# -gt 0 ]]; do
    case $1 in
        --code)
            search_dir=~/Documents/code/
            shift
            ;;
        --meetings)
            search_dir=~/Documents/meetings/
            shift
            ;;
        *)
            # If it's not a flag, treat it as a direct path selection
            selected=$1
            shift
            ;;
    esac
done

if [[ -z $selected ]]; then
    selected=$(find "$search_dir" -mindepth 1 -maxdepth 1 -type d | fzf)
    # selected=$(find "$search_dir" -mindepth 1 -maxdepth 1 -type d | dmenu -l 10 -p "Select a directory")
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
